@startuml

package mastermind.view {
   interface ViewsContainer {
      {abstract} void updateView(Controller controller)
   }
note left: Some MasterMind instance will call <b>ViewsContainer.updateView</b>
}

package mastermind.view.console {
   class CharacterReader {
       Character apply(Vector<Character> validKeys);
   }

   class ViewsContainerConsole <<ConcreteVisitor>> {
       void updateView(Controller controller) <b> { controller.accept(this) }</b>
       void visit (StartController controller) <b> { startConsole.update(controller) }</b>
       void visit (PlayController controller) <b> { playConsole.update(controller) }</b>
       void visit (ResumeController controller) <b> { resumeConsole.update(controller) }</b>
   }

   class StartConsole {
       void update(StartController startController)
   }
   class PlayConsole {
       void update(PlayController playController)
   }
   class ResumeConsole {
       void update(ResumeController resumeController)
   }
}

package mastermind.controller {
   interface Controller <<Element>>{
      {abstract} void setNextState()
      {abstract} void accept(ControllerVisitor controllerVisitor)
   }

   interface StartController <<ConcreteElement>>
   interface PlayController <<ConcreteElement>>
   interface ResumeController <<ConcreteElement>>

   Controller <|--- StartController
   Controller <|-- PlayController
   Controller <|-- ResumeController

   class StartController {
      void accept(Controller controller) <b>{controller.visit(this)}</b>
   }

   class PlayController {
      void accept(Controller controller) <b>{controller.visit(this)}</b>
   }

   class ResumeController {
      void accept(Controller controller) <b>{controller.visit(this)}</b>
   }

   interface ControllerVisitor <<Visitor>> {
      {abstract} void visit(StartController startController);
      {abstract} void visit(PlayController playController);
      {abstract} void visit(ResumeController resumeController);
   }
}


ViewsContainer <|-- ViewsContainerConsole
ControllerVisitor <|-- ViewsContainerConsole

ViewsContainerConsole *--> StartConsole : startConsole
ViewsContainerConsole *--> PlayConsole : playConsole
ViewsContainerConsole *--> ResumeConsole : resumeConsole

PlayConsole --> CharacterReader
ResumeConsole --> CharacterReader

@enduml




