@startuml
autonumber "<b>[00]"

MasterMind -> ControllersContainer: getController(State)
ControllersContainer --> MasterMind: controller

MasterMind -> ViewsContainer: updateView(controller)

participant "ViewsContainerConsole" as ViewsContainerConsole <<ConcreteVisitor>>
create ViewsContainerConsole
ViewsContainer -> ViewsContainerConsole : <<resolve_inheritance>>
ViewsContainer -> ViewsContainerConsole: updateView(controller)

participant "Controller" as Controller <<Element>>
ViewsContainerConsole -> Controller : accept(this)

participant "ConcreteController" as ConcreteController <<ConcreteElement>>
create ConcreteController
Controller -> ConcreteController : <<resolve_inheritance>>
Controller -> ConcreteController : accept(this)

ConcreteController -> ViewsContainerConsole : <<resolve_polymorphism>> visit(this)
ViewsContainerConsole ->] : Perform operation

@enduml