@startuml
autonumber "<b>[00]"

MasterMind -> ControllersContainer: getController(State)
ControllersContainer --> MasterMind: controller

participant "Controller" as Controller <<Element>>
MasterMind -> Controller : accept(controllerVisitor)

participant "ConcreteController" as ConcreteController <<ConcreteElement>>
create ConcreteController
Controller -> ConcreteController : <<resolve_inheritance>>
Controller -> ConcreteController : accept(controllerVisitor)

participant "ControllerVisitor" as ControllerVisitor <<ConcreteVisitor>>

ConcreteController -> ControllerVisitor : visit(this)
ControllerVisitor -> ControllerVisitor : <<resolve_polymorphism>> for visit(ConcreteController)
ControllerVisitor -> ConcreteController : operation-one
...
ControllerVisitor -> ConcreteController : operation-N

@enduml