@startuml

package mastermind.controller {
   interface Controller {
      {abstract} void setNextState()
      {abstract} void accept(ControllerVisitor controllerVisitor)
   }

   class ControllersContainer {
       ControllersContainer(ControllerAbstractFactory controllerFactory)
       Controller getController(State state)
   }

   interface ControllerAbstractFactory <<Abstract Factory>> {
      {abstract}StartController createStartController();
      {abstract}PlayController createPlayController();
      {abstract}ResumeController createResumeController();
   }

   interface StartController {
      {abstract}void initializeGame();
      {abstract}Code getSecretCode();
   }

   interface PlayController {
       {abstract}boolean continueGame();
       {abstract}Response evaluate(Code guessCode);
       {abstract}ValidFigures getValidFigures();
       {abstract}int getAttempt();
       {abstract}int getMaxAttempt();
       {abstract}void codeBreakerWins();
       {abstract}void codeMakerWins();
       {abstract}void registry();
       {abstract}void undo();
       {abstract}void redo();
       {abstract}void quit();
       {abstract}boolean codeDiscovered();
       {abstract}boolean isAborted();
       {abstract}boolean canApplyUndo();
       {abstract}boolean canApplyRedo();
   }

   interface ResumeController {
      {abstract}void resume();
      {abstract}void stop();
   }

   interface ControllerVisitor {
      {abstract}void visit(StartController startController);
      {abstract}void visit(PlayController playController);
      {abstract}void visit(ResumeController resumeController);
   }

   ControllersContainer *-down-> Controller
   Controller ..left. ControllerVisitor

   Controller <|-down- StartController
   Controller <|-down- PlayController
   Controller <|-down- ResumeController

   ControllerVisitor -[dashed]-> StartController
   ControllerVisitor -[dashed]-> PlayController
   ControllerVisitor -[dashed]-> ResumeController

   ControllerAbstractFactory .up.  StartController
   ControllerAbstractFactory .up.  PlayController
   ControllerAbstractFactory .up.  ResumeController
}

@enduml

