@startuml

package mastermind.view {
interface ViewsContainer {
   {abstract} void updateView(Controller controller)
}
}

package mastermind.controller {
   interface Controller <<Element>>{
      {abstract} void setNextState()
      {abstract} void accept(ControllerVisitor controllerVisitor)
   }

   interface StartController <<ConcreteElement>>
   interface PlayController <<ConcreteElement>>
   interface ResumeController <<ConcreteElement>>

   Controller <|-- StartController
   Controller <|-- PlayController
   Controller <|-- ResumeController

   class StartController {
      void updateView(Controller controller) <b>{controller.visit(this)}</b>
   }

   class PlayController {
      void updateView(Controller controller) <b>{controller.visit(this)}</b>
   }

   class ResumeController {
      void updateView(Controller controller) <b>{controller.visit(this)}</b>
   }

   interface ControllerVisitor <<Visitor>> {
      {abstract} void visit(StartController startController);
      {abstract} void visit(PlayController playController);
      {abstract} void visit(ResumeController resumeController);
   }
}

package mastermind.view.console {
   class CharacterReader {
       Character apply();
   }

   class ViewsContainerConsole {
       void updateView(Controller controller) <b> { controller.accept(this) }</b>
       void visit (StartController controller) <b> { startConsole.update(controller) }</b>
       void visit (PlayController controller) <b> { playConsole.update(controller) }</b>
       void visit (ResumeController controller) <b> { resumeConsole.update(controller) }</b>
   }

   class StartConsole <<ConcreteVisitor>> {
       void update(StartController startController)
   }
   class PlayConsole <<ConcreteVisitor>> {
       void update(PlayController playController)
   }
   class ResumeConsole <<ConcreteVisitor>> {
       void update(ResumeController resumeController)
   }
}

ViewsContainer <|-- ViewsContainerConsole
ControllerVisitor <|-- ViewsContainerConsole

ViewsContainerConsole *--> StartConsole : startConsole
ViewsContainerConsole *--> PlayConsole : playConsole
ViewsContainerConsole *--> ResumeConsole : resumeConsole


PlayConsole --> CharacterReader
ResumeConsole --> CharacterReader

StartConsole -[dashed]--> StartController
PlayConsole -[dashed]--> PlayController
ResumeConsole -[dashed]--> ResumeController


@enduml




