@startuml

package java.util {
class Vector
class HashMap
}

package mastermind {
interface MasterMind {
   {abstract}void play();
   {abstract}StartController createStartController();
   {abstract}PlayController createPlayController();
   {abstract}ResumeController createResumeController();
}
}

MasterMind <|-down- mastermind.runtime.MasterMindOverModel


package mastermind.model {
class Code {
   int size();
   Character figureAt(int pos);
}

class Code.Builder {
    Builder add(Character cc)
    int size()
    Code build()
}

class CodeMaker {
 void generateSecretCode()
 Response evaluate(Code guessedCode)
}

class Configuration {
int getMaxAttempt()
void setMaxAttempt(int maxAttempt)
ValidFigures getValidFigures()
void setValidFigures(ValidFigures validFigures)
}

class Game {
   Game(Configuration configuration)
   void initialize()
   boolean continuePlaying()
   void generateSecretCode()
   Response evaluate(Code guessedCode)
   Code getSecretCode()
   int getAttempt()
   int getMaxAttempt()
   ValidFigures getValidFigures()
   -- Memento --
   Game.Memento createMemento()
   void restore(Game.Memento)
}

class Game.Memento {
    Game.Memento(Game)
}

Game -[dashed]- Game.Memento


class Response {
   void putBlack(int ii);
   void putWhite(int ii);
   boolean codeWasBroken();
}

class State {
    enum Value { INITIAL, PLAYING, RESUME, STOP, QUIT }
    
    Value getValue()
    void setValue(Value value)
    void setNextValue() 
    boolean continuePlaying() 
}

Configuration *-right-> ValidFigures

class GameHistoryKeeper {
   GameHistoryKeeper(Game)
   public void registry()
   public boolean canApplyRedo()
   public void redo()
   public boolean canApplyUndo()
   public void undo()
   public void clear()
}

GameHistoryKeeper *--> Game.Memento

}

mastermind.runtime.MasterMindOverModel *--> State
mastermind.runtime.MasterMindOverModel *--> Game

Code.Builder -[dashed]-> Code
Code -[dashed]-> Vector : figures
Code.Builder -[dashed]-> Vector : figures
CodeMaker  *--> Code
CodeMaker  *--> HashMap : figuresWithoutRepetion
CodeMaker --[dashed]-> Code.Builder
CodeMaker --[dashed]-> Response

Game --> Configuration
Game *--> CodeMaker
Game -[dashed]-> Response
Game -[dashed]-> ValidFigures

@enduml
